import type { Common } from "@/content/types";

export const common: Common = {
  localeName: "Română",
  localeShort: "RO",
  nav: {
    home: "Acasă",
    parts: "Piese",
    services: "Servicii",
    info: "Informații",
    articles: "Articole",
    contact: "Contacte",
  },
  cta: {
    call: "Sunați-ne",
    callNow: "Sunați acum",
    write: "Scrieți-ne",
    route: "Traseu",
    quote: "Cereți deviz",
    book: "Programați-vă",
    more: "Detalii",
    all: "Vezi tot",
    back: "Înapoi",
    send: "Trimiteți",
    sending: "Se trimite…",
    menu: "Meniu",
    close: "Închide",
    search: "Căutare",
    viewCatalog: "Vezi catalogul",
    askPrice: "Întrebați prețul",
  },
  labels: {
    phone: "Telefon",
    phones: "Telefoane",
    address: "Adresă",
    hours: "Program",
    email: "E-mail",
    openNow: "Deschis acum",
    closedNow: "Închis acum",
    opensAt: "Deschidem la",
    closesAt: "Închidem la",
    monFri: "Luni – Vineri",
    sat: "Sâmbătă",
    sun: "Duminică",
    closed: "Închis",
    dayOff: "zi liberă",
    breadcrumbHome: "Acasă",
    inThisSection: "În această secțiune",
    relatedServices: "Servicii conexe",
    relatedParts: "Piese asociate",
    quickContact: "Contact rapid",
    workingHours: "Program de lucru",
    findUs: "Cum ne găsiți",
    entranceNote: "Lunca Bâcului 35 A",
    since: "Pe piață din",
    guarantee: "Garanție",
    highlights: "Pe scurt",
    contents: "Cuprins",
  },
  form: {
    title: "Lăsați-ne un mesaj",
    subtitle: "Descrieți defecțiunea și vă răspundem în timpul programului de lucru.",
    name: "Nume",
    namePlaceholder: "Numele dumneavoastră",
    phone: "Telefon",
    phonePlaceholder: "+373 69 000 000",
    car: "Marca și modelul",
    carPlaceholder: "ex.: Ford Transit 2.2 TDCi, 2012",
    topic: "Subiect",
    topicOptions: [
      "Reparație demaror",
      "Reparație alternator",
      "Electrician auto / diagnosticare",
      "Cumpărare piese",
      "Persoane juridice / parc auto",
    ],
    message: "Mesaj",
    messagePlaceholder: "Ce se întâmplă: motorul nu pornește, se aude un clic, bateria se descarcă, becul de încărcare rămâne aprins…",
    consent: "Sunt de acord să fiu contactat la datele indicate în legătură cu această solicitare.",
    success: "Mesaj trimis",
    successBody: "Vă mulțumim. Vă contactăm în timpul programului de lucru. Dacă situația este urgentă, sunați la 069 30 77 08.",
    error: "Mesajul nu a putut fi trimis. Încercați din nou sau sunați la 069 30 77 08.",
    required: "Câmp obligatoriu",
    invalidPhone: "Introduceți un număr de telefon valid",
  },
  footer: {
    tagline: "Reparație de demaroare și alternatoare pentru autoturisme, camioane și utilaj special. Piese, componente și electrician auto în Chișinău.",
    catalogTitle: "Piese și componente",
    servicesTitle: "Servicii",
    infoTitle: "Informații utile",
    contactTitle: "Contacte",
    rights: "Toate drepturile rezervate.",
    madeBy: "Starter Plus",
    legalNote: "„STARTER PLUS” SRL · IDNO 1009600031813",
  },
  notFound: {
    title: "Pagina nu a fost găsită",
    text: "Adresa nu există sau s-a schimbat la reorganizarea site-ului. Găsiți piesa ori serviciul de care aveți nevoie în catalog sau sunați-ne.",
    cta: "Înapoi la pagina principală",
  },
  langSwitch: {
    label: "Limbă",
    ro: "Română",
    ru: "Русский",
  },
};
